# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'js-engine-debug' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for js-engine-debug
  pod 'RxSwift', '5.1.1'
end
